### ISSUE TITLE
Universal support for use in Directives.

### ISSUE THREAD

**Issue by heinbez** [ronzeidman/ng2-ui-auth#94]
Hi,

I'm not sure if I'm just doing something silly. However, when using ng2-ui-auth in a directive as follow

```
@Directive({
    selector: '[prompt-login-action]',
    host: {
        '(click)': 'onClick($event)'
    }
})

export class PromptLoginActionDirective {
    constructor(el: ElementRef, private authService: AuthService) {}

    onClick(event) {

    }
}
```

Universal throws an error "window is not defined"

Any insight would be appreciated.

Thanks!

**Comment by ronzeidman** [comment]
Can you share the call stack?

**Comment by heinbez** [comment]
Sure, here is the error stack.

```
ERROR { ReferenceError: window is not defined
    at ConfigService.isCordovaApp (/var/www/[project]/dist/server.js:16010:18)
    at new ConfigService (/var/www/[project]/dist/server.js:15831:29)
    at ServerAppModuleInjector.get (ng:///ServerAppModule/module.ngfactory.js:160:71)
    at ServerAppModuleInjector.get (ng:///ServerAppModule/module.ngfactory.js:165:109)
    at ServerAppModuleInjector.get (ng:///ServerAppModule/module.ngfactory.js:170:99)
    at ServerAppModuleInjector.get (ng:///ServerAppModule/module.ngfactory.js:205:93)
    at ServerAppModuleInjector.getInternal (ng:///ServerAppModule/module.ngfactory.js:382:51)
    at ServerAppModuleInjector.NgModuleInjector.get (/var/www/[project]/dist/server.js:4302:44)
    at resolveDep (/var/www/[project]/dist/server.js:11764:45)
    at createClass (/var/www/[project]/dist/server.js:11617:35)
  __zone_symbol__currentTask: 
   ZoneTask {
     _zone: 
      Zone {
        _properties: [Object],
        _parent: [Object],
        _name: 'angular',
        _zoneDelegate: [Object] },
     runCount: 0,
     _zoneDelegates: null,
     _state: 'notScheduled',
     type: 'microTask',
     source: 'Promise.then',
     data: undefined,
     scheduleFn: undefined,
     cancelFn: null,
     callback: [Function],
     invoke: [Function] } }
```

And I call my directive from app module:

```
export class MyAuthConfig extends CustomConfig {
    ...
}

@NgModule({
   ...
   imports: [
        ...
        Ng2UiAuthModule.forRoot(MyAuthConfig),
   ],
   declarations: [
	 ...
        PromptLoginActionDirective
   ].
   exports: [AppComponent]
})
export class AppModule {}
```

**Comment by ronzeidman** [comment]
Try looking at https://github.com/ronzeidman/ng2-ui-auth/pull/73

**Comment by heinbez** [comment]
Great! Thanks.
